# database-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword" # Update to a strong password
        - name: MYSQL_DATABASE
          value: "mydatabase"
        - name: MYSQL_USER
          value: 'dbuser'
        - name: MYSQL_PASSWORD
          value: 'dbpassword'
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: webapp
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: database
